<?php

namespace ContactBookBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{
    public function findById($id)
    {
        $dql = "SELECT address FROM ContactBookBundle:Address address WHERE address.contact = :id";
        $addresses = $this->getEntityManager()->createQuery($dql)->setParameter('id', $id)->getResult();
        return $addresses;
    }
}
