<?php

namespace ContactBookBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TelephoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelephoneRepository extends EntityRepository
{
    public function findById($id)
    {
        $dql = "SELECT telephone FROM ContactBookBundle:Telephone telephone WHERE telephone.contact = :id";
        $telephones = $this->getEntityManager()->createQuery($dql)->setParameter('id', $id)->getResult();
        return $telephones;
    }
}
